language: php

php:
    - "5.5"
    - "5.6"
    - "7.0"
    - "hhvm"

before_script:
    - pecl -q install mongo && echo "extension=mongo.so" >> `php --ini | grep "Loaded Configuration" | sed -e "s|.*:\s*||"`
    - composer install --prefer-dist --dev
    - phpenv rehash

notifications:
  email: false

matrix:
  allow_failures:
    - php: hhvm
    - php: "7.0"
